import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const params=new URLSearchParams(location.search),restaurant=params.get("restaurant")||"Orderly Restaurant",tableParam=params.get("table")||"";
const cfg=window.ORDERLY_SUPABASE_CONFIG||{};const supabase=cfg.url&&cfg.anonKey&&!String(cfg.url).includes("REPLACE_ME")?createClient(cfg.url,cfg.anonKey):null;
let cart=[];const menuItems=[{id:"m1",name:"Masala Dosa",desc:"Crispy dosa with potato filling",price:120,category:"South Indian"},{id:"m2",name:"Cold Coffee",desc:"Chilled, creamy and refreshing",price:80,category:"Drinks"},{id:"m3",name:"Paneer Butter Masala",desc:"Rich tomato gravy with paneer",price:210,category:"Main Course"},{id:"m4",name:"Margherita Pizza",desc:"Thin crust with mozzarella and basil",price:250,category:"Pizza"},{id:"m5",name:"Veg Hakka Noodles",desc:"Wok-tossed noodles with vegetables",price:170,category:"Main Course"},{id:"m6",name:"Masala Fries",desc:"Crispy fries with house seasoning",price:90,category:"Sides"}];
const $=id=>document.getElementById(id);$("restaurantName").textContent=restaurant;$("restaurantNameSmall").textContent=restaurant;$("tableNo").value=tableParam;$("tableBadge").textContent=tableParam||"—";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function renderMenu(){const cats=[...new Set(menuItems.map(x=>x.category))];$("menuItems").innerHTML=cats.map(c=>'<div class="menu-category"><h3>'+esc(c)+'</h3><div class="category-grid">'+menuItems.filter(x=>x.category===c).map(m=>'<article class="menu-card"><div><div class="menu-name">'+esc(m.name)+'</div><div class="menu-desc">'+esc(m.desc)+'</div></div><div class="menu-row"><strong class="menu-price">₹'+m.price+'</strong><button class="btn primary" data-add="'+m.id+'">Add</button></div></article>').join("")+'</div></div>').join("");document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(b.dataset.add));}
function add(id){const x=menuItems.find(x=>x.id===id),f=cart.find(x=>x.id===id);f?f.qty++:cart.push({...x,qty:1});renderCart();}function qty(id,d){const i=cart.findIndex(x=>x.id===id);if(i<0)return;cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);renderCart();}
function renderCart(){$("orderList").innerHTML=cart.length?cart.map(x=>'<div class="order-item"><div><strong>'+esc(x.name)+'</strong><div class="small">₹'+x.price+' each</div></div><div class="order-controls"><button class="qty" data-q="'+x.id+'" data-d="-1">−</button><span>'+x.qty+'</span><button class="qty" data-q="'+x.id+'" data-d="1">+</button><strong>₹'+x.price*x.qty+'</strong></div></div>').join(""):'<div class="small">Your cart is empty.</div>';$ ("cartTotal").textContent="₹"+cart.reduce((s,x)=>s+x.price*x.qty,0);$("itemCount").textContent=cart.reduce((s,x)=>s+x.qty,0);document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>qty(b.dataset.q,+b.dataset.d));}
$("clearCart").onclick=()=>{cart=[];renderCart();};$("tableNo").oninput=e=>$("tableBadge").textContent=e.target.value.trim()||"—";$("custName").oninput=e=>$("guestNameDisplay").textContent=e.target.value.trim()||"—";
async function placeOrder(){const guest=$("custName").value.trim(),table=$("tableNo").value.trim(),phone=$("phone").value.trim();if(!guest)return msg("Please enter your name.");if(!table)return msg("Please enter or scan a table number.");if(!cart.length)return msg("Add at least one item to your cart.");const items=cart.map(x=>({id:x.id,name:x.name,price:x.price,qty:x.qty})),total=items.reduce((s,x)=>s+x.price*x.qty,0);try{if(!supabase)throw Error("Supabase not configured");const {data,error}=await supabase.from("orders").insert({restaurant_name:restaurant,table_no:table,guest_name:guest,phone,items,total,status:"new"}).select("id").single();if(error)throw error;cart=[];renderCart();$("custName").value="";$("phone").value="";$("orderMsg").innerHTML='<div class="success">Order <strong>#'+String(data.id).slice(-6).toUpperCase()+'</strong> received for table <strong>'+esc(table)+'</strong>.</div>';}catch(e){console.error(e);msg("Demo mode: order could not reach Supabase. Add your Supabase config to enable the live dashboard.");}}
function msg(x){$("orderMsg").textContent=x;}$("placeOrderBtn").onclick=placeOrder;renderMenu();renderCart();