-- Orderly database schema for Supabase
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  restaurant_name text not null,
  table_no text not null,
  guest_name text not null,
  phone text,
  items jsonb not null default '[]'::jsonb,
  total numeric(10,2) not null default 0,
  status text not null default 'new' check (status in ('new','preparing','ready','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_table_idx on public.orders(table_no);

alter table public.orders enable row level security;

-- Classroom/demo policies. Tighten these before public production use.
create policy "demo can create orders" on public.orders for insert to anon with check (true);
create policy "demo can read orders" on public.orders for select to anon using (true);
create policy "demo can update orders" on public.orders for update to anon using (true) with check (true);

-- Required for Supabase Realtime dashboard updates.
alter table public.orders replica identity full;

-- Enable the table in the Realtime publication if it is not already present.
alter publication supabase_realtime add table public.orders;
